### ISSUE TITLE
NPE when Stamping a crafttweakered metal

### ISSUE THREAD

**Issue by Ligands** [DaedalusGame/Soot#30]
I've added Constantan to the Melter / Stamper / Mixer, and can melt down the fluid just fine, but attempting to stamp it out into either bars or plates causes a NullPointerException:

```
java.lang.NullPointerException: Ticking block entity
	at soot.util.IngredientCraftTweaker.getSize(IngredientCraftTweaker.java:36)
	at soot.recipe.RecipeStamper.getInputConsumed(RecipeStamper.java:26)
	at soot.tile.TileEntityStamperImproved.update(TileEntityStamperImproved.java:76)
	at net.minecraft.world.World.redirect$tileEntityUpdate$zbf000(World.java:5129)
	at net.minecraft.world.World.updateEntities(World.java:1832)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
```

(Full crash log: https://paste.dimdev.org/qunovecizi.txt)

This is the relevant Crafttweaker code: 

```
Mixer.add(<liquid:moltenconstantan>*8, [<liquid:copper>*4, <liquid:nickel>*4]);
Melter.add(<liquid:moltenconstantan>*144, <ore:ingotConstantan>);
Melter.add(<liquid:moltenconstantan>*16, <ore:nuggetConstantan>);
Melter.add(<liquid:moltenconstantan>*144, <ore:plateConstantan>);
Melter.add(<liquid:moltenconstantan>*144, <ore:dustConstantan>);
Stamper.add(<thermalfoundation:material:164>, <liquid:moltenconstantan>*144, <embers:stamp_bar>);
Stamper.add(<thermalfoundation:material:356>, <liquid:moltenconstantan>*144, <embers:stamp_plate>);
```

The moltenconstantan fluid has been added with Content Tweaker as there is no molten constantan in my selection of mods, but it's all been set up correctly so I'm not sure if it's significant.

**Versions:**
Soot: 0.10 - 0.12 (tried each of em)
Embers: 0.230
Forge: 14.23.3.2675

**Comment by DaedalusGame** [comment]
oops

**Comment by DaedalusGame** [comment]
fix is up on curse now

**Comment by Ligands** [comment]
many thanks!
